### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by weiguangzhao** [ferjad/3DCZSL#1]
Hi, thanks for your great work. When I try to download the dataset, it failed again and again. To this end, I wonder know if there is a backup way to download the dataset, like baidupan or wetransfer. Thanks.

**Comment by ferjad** [comment]
Thank you for your interest in our work. I just checked and the download link is working for me. 
If you can recommend a file hosting service I will be happy to reupload it. baidupan seems to be Chinese only and wetransfer only supports files up to 2GB.

**Comment by weiguangzhao** [comment]
Thank you. I copy the file to my google drive and download it successfully.
